const BUY_POKEMON = 'BUY_POKEMON';
const RETURN_POKEMON = 'RETURN_POKEMON';

const BUY_CONSOLE = 'BUY_CONSOLE';
const RETURN_CONSOLE = 'RETURN_CONSOLE';

const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILURE = 'FETCH_FAILURE';

export {
    BUY_POKEMON,
    RETURN_POKEMON,
    BUY_CONSOLE,
    RETURN_CONSOLE,
    FETCH_REQUEST,
    FETCH_SUCCESS,
    FETCH_FAILURE
}