const BUY_POKEMON = 'BUY_POKEMON';
const RETURN_POKEMON = 'RETURN_POKEMON';

const BUY_CONSOLE = 'BUY_CONSOLE';
const RETURN_CONSOLE = 'RETURN_CONSOLE';

export {
    BUY_POKEMON,
    RETURN_POKEMON,
    BUY_CONSOLE,
    RETURN_CONSOLE
}